export class Patient {
    active:number
    assurance:number
    createdAt:string
    dateNaissance:string
    email:string
    genre:string
    id:number
    lieuHabitation:string
    login:string
    nom:string
    numeroAssure:string
    password:string
    prenoms:string
    profession:string
    role:string
    tauxCouverture:number
    tel:string
    tel2:string
    updatedAt:string
    version:number
}
