name: Cypress Test
'on': [push]

jobs:
  build_and_preview:
    if: '${{ github.event.push.head.repo.full_name == github.repository }}'
    run-on: ubuntu-latest
    steps:
      -name: Checkout
      -uses: actions/checkout@v2
      -name: Cypress run
      -run: npm run build
      -uses: cypress-io/github-action@v2
       with:
         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
         repoToken: ${{ secrets.GITHUB_TOKEN }}
         projectId: 4ybk56

