name: Cypress Test
on: [push]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
      - name: Cypress run
      - uses: cypress-io/github-action@v2
        with:
          record: true
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          CYPRESS_RECORD_KEY: '${{ secrets.CYPRESS_RECORD_KEY }}'
